#!/usr/bin/env python

from compat import open_utf8

Import("env")

env.platform_sources = []

env.add_source_files(env.platform_sources, "sfwl.cpp")

lib = env.add_library("platform", env.platform_sources)
env.Prepend(LIBS=[lib])
