#!/usr/bin/env python

from compat import open_utf8

Import("env")

env.main_sources = []

env.add_source_files(env.main_sources, "main.cpp")
lib = env.add_library("main", env.main_sources)
env.Prepend(LIBS=[lib])
