#!/usr/bin/env python

Import("env")

from platform_methods import run_in_subprocess
import platform_x11_builders

common_x11 = [
]

prog = env.add_program("#bin/pmlpp", common_x11)

if env["debug_symbols"] and env["separate_debug_symbols"]:
    env.AddPostAction(prog, run_in_subprocess(platform_x11_builders.make_debug_x11))
