#!/usr/bin/env python

Import("env")

from platform_methods import run_in_subprocess
import platform_x11_builders

common_x11 = [
]

if "udev" in env and env["udev"]:
    common_x11.append("libudev-so_wrap.c")

prog = env.add_program("#bin/pandemonium", common_x11)

if env["debug_symbols"] and env["separate_debug_symbols"]:
    env.AddPostAction(prog, run_in_subprocess(platform_x11_builders.make_debug_x11))
